#ifndef __WINJECTOR_HELPER_H__
#define __WINJECTOR_HELPER_H__

typedef enum
{
  ZED_WINJECTOR_ERROR_INVALID,
  ZED_WINJECTOR_ERROR_OPEN_PROCESS_FAILED,
  ZED_WINJECTOR_ERROR_GRAB_THREAD_FAILED,
  ZED_WINJECTOR_ERROR_TRICK_THREAD_FAILED
} ZedWinjectorError;

#endif
